// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msjzavmbckfaqennwbym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zanphdm1iY2tmYXFlbm53YnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTg3MzAsImV4cCI6MjA3MzQ3NDczMH0.TOrrmeXwAeKqXtWJSh_l9amy8Wkd1HUYZNyiQOHNHZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});